### ISSUE TITLE
ImportFailed.Result returns <traceback object>

### ISSUE THREAD

**Issue by stefanvogelch** [VMelnalksnis/PaperlessDotNet#284]
Sometimes, if uploading document fails, the result (DocumentCreationResult) says something like this:

<traceback object at 0x7f4f3b529980>. 

I cast the result like this:
if (result is ImportFailed resFailed)

and look at resFailed.Result

This occures not always, only in about 50% percent of the cases. If it works correctly, the result is shown correctly, saying someting like this:
Test-Report.pdf:   Not consuming Test-Report.pdf: It is a duplicate   of Test-Report (#117).

**Comment by VMelnalksnis** [comment]
Can you check the logs to see if there are any more details why it failed? The `Result` property is whatever Paperless returns, I'm guessing it returns some error object which is then converted to `<traceback object at 0x7f4f3b529980>`, instead of a readable error message.

Some other clients had similar issue with duplicate imports, see https://github.com/tb1337/paperless-api/issues/61. I'll see if there's something that can be fixed, but looks like an issue in Paperless itself.

**Comment by VMelnalksnis** [comment]
From testing it looks like this happens when creating duplicate documents and checking the task status too fast. From the linked issue and my testing it looks like 250ms is good enough.
